Update meraki_cv.py
Getting this issue when running this script:

"Traceback (most recent call last):
  File "meraki_cv.py", line 239, in <module>
    client.connect(SERVER_IP, 1883, 300)
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out"


- patch is to change line 238 to connect to localhost since I'm running the mqtt in the same client executing this script.